[package]
name = "gloria-victis-bot"
version = "0.1.0"
edition = "2018"

[features]
opencv1 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
anyhow = "1.0"
inputbot = "0.5.0"
env_logger = "0.9"
log = "0.4"
winapi = { version = "0.3.8", features = ["d3d11", "d3dcommon", "dxgi", "dxgi1_2", "dxgitype", "ntdef", "unknwnbase", "windef", "winerror", "winuser"] }
wio = "0.2.2"
winit = "0.24"
imgui = "0.7"
imgui-glium-renderer = "0.7"
imgui-winit-support = "0.7"
clipboard = "0.5"
glium = { version = "0.29", default-features = true }
image = "0.23.14"
imageproc = { version = "0.22", features = ["display-window"] }
# opencv = {version = "0.53" }
tokio = {version = "1.9", features = ["full", "macros"]}
tesseract = "0.9"
opencv = {version = "0.53", features =  ["clang-runtime"]}
[dev-dependencies]
vcpkg = "0.2"