[package]
name = "gloria-victis-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = "0.5.0"
winapi = { version = "0.3.8", features = ["d3d11", "d3dcommon", "dxgi", "dxgi1_2", "dxgitype", "ntdef", "unknwnbase", "windef", "winerror", "winuser"] }
wio = "0.2.2"
image = "0.23.14"
imageproc = { version = "0.22", features = ["display-window"] }
# opencv = {version = "0.53"}
# opencv = {version = "0.53", features =  ["clang-runtime"]}