[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.25.0", features = ["build"]}

[build-dependencies]
windows = { version = "0.25.0", features = ["build"]}
